#!/bin/bash
echo -e "please enter physics marks: \c"
read -r p
echo -e "please enter chemistry marks: \c"
read -r c
echo -e "please enter biology marks: \c"
read -r b
if [ $p -ge 35 -a $c -ge 35 -a $b -ge 35 ];
then
total=`expr $p + $c + $b`
avg=`$total/3
echo "total marks is = $total"
echo "avg marks is = $avg
       if [ $avg -ge 75 ];
       then
       echo "you got distinction"
       elif [ $avg -ge 60 -a $avg -le 75 ];
       then
       echo "you got first class"
       elif [ $avg -ge 55 -a $avg -le 60 ];
       then
       echo "you got second class"
       elif [ $avg -ge 50 -a $avg -le 55 ];
       then 
       echo "you got third class"
       fi
else
echo "sorry you have not cleared the exam"
fi
